#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

foamListTimes -rm
rm -r constant/polyMesh
rm -r 0

#------------------------------------------------------------------------------
